# server port
server:
  port: 9000
  servlet:
    context-path: /manage

spring:
  # base info
  application:
    name: management-server

  # datasource config
  datasource:
    url: jdbc:mysql://101.201.254.58:3306/management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1qazXSW@
    driver-class-name: com.mysql.cj.jdbc.Driver

  # security config 【spring boot 需要引入对应依赖生效】
  security:
    user:
      name: user
      password: 123456

# mybatis config
mybatis:
  typeAliasesPackage: com.liuw.management.db.domain.*
  mapperLocations: classpath:mapper/*/*.xml
  #configLocation: classpath:/mybatis-config.xml

# mybatis控制台日志
logging:
  level:
    com.liuw.management.db.mapper : debug
